### ISSUE TITLE
Power is not "consumed"

### ISSUE THREAD

**Issue by romain-jacob** [cpignata/powerbench#2]
Nit: Power is the rate of energy consumption. It is not "consumed." It is drawn. 

(I don't mean to be mean to be pedantic, but I think it's important to be precise in the wording, especially in IETF context)

**Comment by cpignata** [comment]
Nothing pedantic about this -- it's also one of my pet-peeves, and important to have precision.

**Comment by cpignata** [comment]
Fixed in #4
